/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Serversock;


/**
 *
 * @author Josue Bonilla
 */
public class EditTagx extends javax.swing.JFrame {
    panelConfig pc = null;
    panelSeleccion ps =null;
    static String path = "";

    public EditTagx() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan = new javax.swing.JPanel();
        jMb = new javax.swing.JMenuBar();
        jselec = new javax.swing.JMenu();
        jm1 = new javax.swing.JMenuItem();
        jconf = new javax.swing.JMenu();
        jmc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccione un archivo de audio");
        setResizable(false);

        javax.swing.GroupLayout jPanLayout = new javax.swing.GroupLayout(jPan);
        jPan.setLayout(jPanLayout);
        jPanLayout.setHorizontalGroup(
            jPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanLayout.setVerticalGroup(
            jPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jselec.setText("Archivo");

        jm1.setText("Seleccionar");
        jm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm1ActionPerformed(evt);
            }
        });
        jselec.add(jm1);

        jMb.add(jselec);

        jconf.setText("Editar");

        jmc.setText("Configuracion");
        jmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcActionPerformed(evt);
            }
        });
        jconf.add(jmc);

        jMb.add(jconf);

        setJMenuBar(jMb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm1ActionPerformed
        // TODO add your handling code here:
        ps = new panelSeleccion();
        ps.setSize(455, 95);
        ps.setLocation(5,5);
        jPan.removeAll();
        jPan.add(ps);
        jPan.revalidate();
        jPan.repaint();
        if(pc !=null){
            ps.setHostPuerto(pc.getHost(), Integer.parseInt(pc.getPuerto()));
        }
        
    }//GEN-LAST:event_jm1ActionPerformed

    private void jmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcActionPerformed
        // TODO add your handling code here:
        pc = new panelConfig();
        pc.setSize(455, 365);
        pc.setLocation(5,5);
        jPan.removeAll();
        jPan.add(pc);
        jPan.revalidate();
        jPan.repaint();
        
    }//GEN-LAST:event_jmcActionPerformed
    
    public void iniciar(){
        panelUser pu = new panelUser();
        pu.setSize(455, 365);
        pu.setLocation(5, 5);
        jPan.removeAll();
        jPan.add(pu);
        jPan.revalidate();
        jPan.repaint();
    }
    
    public String getpath(){
        return this.path;
    }
    
    public void setpath(String path){
        System.out.println("pathh "+path);
        this.path = path;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTagx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTagx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTagx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTagx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTagx().setVisible(true);
            }
        });
    }
    /* Create and display the form */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMb;
    private javax.swing.JPanel jPan;
    private javax.swing.JMenu jconf;
    private javax.swing.JMenuItem jm1;
    private javax.swing.JMenuItem jmc;
    private javax.swing.JMenu jselec;
    // End of variables declaration//GEN-END:variables
}
