/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Serversock;
import java.io.File;
import Serversock.Mp3Object;
import java.awt.event.ActionEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Chack
 */
public class panelSeleccion extends javax.swing.JPanel {
    // Esta variable se usa en dos metodos diferentes por esa razon en global
    File archivo = null;
    // Esta variable se usa en el boton examinar y es global para evitar cambiar el ultimo valor dado.
    String path = "";
    String hosts = "localhost";
    int puerto = 5000;
    /**
     * Creates new form panelSeleccion
     */
    public panelSeleccion() {
        initComponents();
        noMostrar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lanime = new javax.swing.JLabel();
        Tartista = new javax.swing.JTextField();
        Ttitulo = new javax.swing.JTextField();
        Tanime = new javax.swing.JTextField();
        Jenviar = new javax.swing.JButton();
        Jborrar = new javax.swing.JButton();
        Texa = new javax.swing.JTextField();
        Bexa = new javax.swing.JButton();
        lrellenar = new javax.swing.JLabel();
        lartista = new javax.swing.JLabel();
        lcancion = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(455, 365));

        lanime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lanime.setText("Anime: ");
        lanime.setAutoscrolls(true);

        Tartista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Ttitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Tanime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tanime.setToolTipText("Opcional");

        Jenviar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Jenviar.setText("Enviar");
        Jenviar.setAutoscrolls(true);
        Jenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenviarActionPerformed(evt);
            }
        });

        Jborrar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Jborrar.setText("Borrar");
        Jborrar.setAutoscrolls(true);
        Jborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JborrarActionPerformed(evt);
            }
        });

        Bexa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Bexa.setText("Examinar");
        Bexa.setAutoscrolls(true);
        Bexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexaActionPerformed(evt);
            }
        });

        lrellenar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lrellenar.setText("Editar");
        lrellenar.setAutoscrolls(true);

        lartista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lartista.setText("Artista: ");
        lartista.setAutoscrolls(true);

        lcancion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lcancion.setText("Titulo: ");
        lcancion.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Texa, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Bexa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lrellenar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lartista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Tartista, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lcancion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lanime)
                        .addGap(31, 31, 31)
                        .addComponent(Tanime, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Jenviar)
                        .addGap(30, 30, 30)
                        .addComponent(Jborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bexa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(lrellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lartista, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tartista, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcancion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lanime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tanime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenviarActionPerformed
        // TODO add your handling code here:
        Mp3Object tags = new Mp3Object();
        //si el campo artista esta vacio se muestra un mensaje
        if(!Tartista.getText().trim().equalsIgnoreCase("")){
            tags.setArtist(Tartista.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "El campo Artista esta vacio","Aviso" ,JOptionPane.WARNING_MESSAGE);
        }
        //si el campo titutlo esta vacio se muestra un mensaje
        if(!Ttitulo.getText().trim().equalsIgnoreCase("")){
            tags.setTitle(Ttitulo.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "El campo Titulo esta vacio","Aviso" ,JOptionPane.WARNING_MESSAGE);
        }
        //si el campo anime tiene como valor ??? se manda vacio.
        if(Tanime.getText().trim().equalsIgnoreCase("???")){
            tags.setAnime("");
        }else{
            tags.setAnime(Tanime.getText().trim());
        }
        //si el campo artista y titulo estan vacios no se envia nada.
        if(!Tartista.getText().trim().equalsIgnoreCase("")&&!Ttitulo.getText().trim().equalsIgnoreCase("")){
            byte[] datos = new byte[(int)archivo.length()];
            FileInputStream in = null;
            try {
                in = new FileInputStream(archivo);
                in.read(datos);
                in.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EditTagx.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(EditTagx.class.getName()).log(Level.SEVERE, null, ex);
            }
            tags.setMp3Files(datos);
            System.out.println("datos de antes de envio "+hosts+" "+puerto);
            SocketEnvio se = new SocketEnvio(hosts, puerto);
            se.enviando(tags);
            JborrarActionPerformed(evt);
        }

    }//GEN-LAST:event_JenviarActionPerformed

    private void JborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JborrarActionPerformed
        // borra los siguientes campos y los deshabilita.
        Tartista.setText("");
        Ttitulo.setText("");
        Tanime.setText("");
        Texa.setText("");
        noMostrar(false);
    }//GEN-LAST:event_JborrarActionPerformed

    private void BexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexaActionPerformed
        JFileChooser chooser = null;//creando variable de tipo JfileChooser
        chooser = new JFileChooser();//creando objeto de tipo jFileChooser
        chooser.setAcceptAllFileFilterUsed(false);//deshabilitando el que pueda mostrar cualquier archivo
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("MP3 Audio", "mp3"));//especificando tipo de archivo a aceptar y mostrar
        EditTagx et = new EditTagx();
        if (!et.getpath().equals("")) {
            chooser.setCurrentDirectory(new File(et.getpath()));//recordando el ultimo directorio visitado       
        }else{
            
        }
        int yesno = chooser.showOpenDialog(this);//Mostrando JFileChooser
        try {
            archivo = chooser.getSelectedFile();//obteniendo archivo
            path = archivo.getAbsolutePath();//obteniendo la ruta del archivo
            Texa.setText(path);//mostrando ruta del archivo
        } catch (NullPointerException e) {
            System.out.println("No se selecciono un archivo. El archivo es " + e.getMessage());
        }
        if (yesno == 0) {//sino se selecciona un archivo. No se intentara extraer informacion de el.
            FileTagx ft = new FileTagx(path);
            //obteniendo informacion del archivo y mostrando en los campos correspondientes.
            Tartista.setText(ft.getFileTags().getArtist());
            Ttitulo.setText(ft.getFileTags().getTitle());
            Tanime.setText("???");
            noMostrar(true);
            et.setpath(new File(path).getParentFile().toString());
        }
    }//GEN-LAST:event_BexaActionPerformed

    public void noMostrar(boolean valor) {
        //deshabilita todos estos objetos en la ventana
        Tartista.setEnabled(valor);
        Ttitulo.setEnabled(valor);
        Tanime.setEnabled(valor);
        Jenviar.setEnabled(valor);
        Jborrar.setEnabled(valor);
        lrellenar.setEnabled(valor);
        lartista.setEnabled(valor);
        lcancion.setEnabled(valor);
        lanime.setEnabled(valor);
        //ancho*alto. Cambia las dimensiones de la ventana.
        if (valor) {
            this.setSize(455, 365);
        } else {
            this.setSize(455, 95);
        }
    }
    
    public void setHostPuerto(String h, int p){
        hosts = h;
        puerto = p;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bexa;
    private javax.swing.JButton Jborrar;
    private javax.swing.JButton Jenviar;
    private javax.swing.JTextField Tanime;
    private javax.swing.JTextField Tartista;
    private javax.swing.JTextField Texa;
    private javax.swing.JTextField Ttitulo;
    private javax.swing.JLabel lanime;
    private javax.swing.JLabel lartista;
    private javax.swing.JLabel lcancion;
    private javax.swing.JLabel lrellenar;
    // End of variables declaration//GEN-END:variables
}
